### ISSUE TITLE
Driver Not Updating?

### ISSUE THREAD

**Issue by Kleinja** [kirkhansen/hubitat-weatherstack#7]
I have been seeing issues with my driver today not refreshing. Pull from Hubitat log below. I reset my API Key on Weatherstack to see if that would fix, but it did not. Still getting the same error before and after resetting the API Key

`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed on line 281`

![image](https://user-images.githubusercontent.com/34429413/163831870-3108681b-c993-499a-96f8-0616910e0990.png)

**Comment by kirkhansen** [comment]
Seems https://api.sunrise-sunset.org has failed to update their SSL cert; expired on 04/15/2022.

**Comment by kirkhansen** [comment]
It appears they allow/host an http only version. I'm tempted to just update the main repo with that, but for now, if you want, you can update https://github.com/kirkhansen/hubitat-weatherstack/blob/dev/weatherstack.groovy#L279 to be http vs https:

`http://api.sunrise-sunset.org/json?lat=$latitude&lng=$longitude&date=$forDate&formatted=0`

**Comment by kirkhansen** [comment]
I contacted them about getting their cert updated. Will post back if I hear anything.

**Comment by kirkhansen** [comment]
They updated the cert, and it's working again for me. Thanks for raising the issue!

**Comment by Kleinja** [comment]
Thanks so much for digging into this! It is now working again for me as well!
