### ISSUE TITLE
Handshake Exception Error

### ISSUE THREAD

**Issue by Kleinja** [kirkhansen/hubitat-weatherstack#8]
I'm seeing some sort of handshake exception in the logs with poll and refresh. Wasn't home over the weekend, but it looks like the driver stopped updating 7-22 at noon. 

Any thoughts as to what is going on?

![image](https://user-images.githubusercontent.com/34429413/180792730-e0e657c9-7217-4689-a99d-72feba758057.png)

**Comment by kirkhansen** [comment]
Looks like the same issue as #7. I'll reach out again and see if they can get their cert updated again.

**Comment by Kleinja** [comment]
Perfect, thanks for looking into it!

**Comment by Kleinja** [comment]
Hey Kirk,

Any update on this? Seems it still wasn't working for me today. I was able to tweak the driver code slightly and comment out some code and it seems to be working for me again (from what I can tell in a couple hours time). I only use this driver for illuminance and temperature, so most of the other variables are not necessary for me. 

I commented out lines: (from the page https://github.com/kirkhansen/hubitat-weatherstack/blob/dev/weatherstack.groovy )

193-202
205-209
278-286

It seems the API call and variables within these lines of code is adding the ability to get sunrise and sunset data? I have a few suggestions to potentially solve this issue for me:
1) Would it be possible to update the driver and if the API returned null to ignore the error or not update the variables for sunrise / sunset but update everything else? 
2) Could you add a preferences switch to ignore these variables and not get sunrise / sunset data. 
3) I'm no expert in groovy by any means, so I am not sure if this next option would even be possible. Could we check illuminance first, assuming it would update even if the other code returned an error? This way, even if there was an error with sunrise / sunset I wouldn't see it. 

It seems for the time being removing the lines of code mentioned above everything else seems to be working fine. I want to check in the morning to ensure the illuminance data is updating correctly. I definitely don't want to break any functionality for any others who might be using this data. Personally, not sure what the best method of approach would be depending on how others use the driver. 


I also added one line to add a 6 hour Poll as well: '0 0 */6 ? * * *':'6 hours'
This was added on line 119, pushing everything else down one line. 
Would it be possible to add this line into the main code so if I update with HPM I don't have to manually add it back in?

**Comment by kirkhansen** [comment]
I haven't heard anything yet. They expose the api as plain http. I'll plan to add a mechanism to try https, and fall back to http, and if it still fails, we can log it and move on or something. 

I can add that cron schedule. Feel free to submit a PR if you want as well.

I'll think a bit more on the additional suggestions, thanks!

**Comment by Kleinja** [comment]
That sounds like a good plan. Turns out the lines I removed didn't help with illuminance data updating. All it does is keep the driver from posting an error in the logs. 

Submitted a PR as well for the polling frequency

**Comment by kirkhansen** [comment]
Still haven't heard anything from them. I'll try and get to this tonight.

> Submitted a PR as well for the polling frequency

I'm not seeing the PR in this repo, btw.

**Comment by Kleinja** [comment]
Thanks for getting this up and working again! Seems like the driver for me is updating properly again. Apologies on the PR, I'm a Github novice and didn't properly submit it. Looks like you added the change in already, so I won't bother with it anymore. Thanks again for the support!
